
#an_imp  = ['                               .     ']
#an_imp += ['                                     ']
an_imp  = [' .   ,              . D     .        ']
an_imp += ['         .        .    $    M.       ']
an_imp += ['                      .8.   N        ']
an_imp += ['      .                O.  .Z        ']
an_imp += ['    ZNN8OZOOZN.   ..  M?  IO         ']
an_imp += ['        ..7$IZMM$MMDO8M MOODM        ']
an_imp += ['          . D?7OMZOZMMO8$I         ..']
an_imp += ['         ...  ..8$ONNN87M  .   ..  . ']
an_imp += ['  ..    ..=  .  .,DD8DDZM$    .      ']
an_imp += ['       .::~:   M$7NMM...M  .         ']
an_imp += ['      D+D+?+  I+?ODNDMMM .           ']
an_imp += ['     .NMM7?+  =I78N7MZNM.. .         ']
an_imp += ['.   D?N$??+~  +I8+$M88DZM    .       ']
an_imp += ['     MDMO?N.  $DM8MZMOMD8N           ']
an_imp += ['       MM888ZZZMMOO8MM.NDM .         ']
an_imp += ['        .,~ ? ..OI$ZN.M8DN  .        ']
an_imp += ['               $$Z$88MZNM.  .M.M     ']
an_imp += ['            .7ZO7OOND$$8M  8M8DZZ    ']
an_imp += ['           8NMNNM$MMDZDD ..8N.MZOM.  ']
an_imp += ['         MNMMM  MO $OMDN   .  .DDMM  ']
an_imp += ['        .DMNM  .$..=?DDM        NM.  ']
an_imp += ['  , .    .MOM  MN, MMI7DM  ..  .ND   ']
an_imp += ['  .~:.    .MM  DN, .   MM8=.:..NO    ']
an_imp += ['  ..=.=~ .NN   .IO. .,  MM+~ .7$     ']
an_imp += [' .:+..+I$$OM.    M$M=. MMNMM$7.      ']
an_imp += [' ~=.=:MI7$OM?+: .  +M?7NZDN~I..      ']
an_imp += [' ?+:$OOII$NNI.,=.  I,.D7Z7$OO:~      ']
an_imp += [' ,+?IDO$+,+?=:.    .IZ++$I$8?        ']
an_imp += ['    .?..  :.I+      .~MN?MI~~.    .  ']
an_imp += ['     .~.  .            .,. :..       ']
#an_imp += ['                                     ']
#an_imp += ['                                     ']
